version: '3.5'

services:
  service:
    build:
      context: ./service
    ports:
      - "3000:3000"
    dns:
      - 172.17.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: service
    networks:
      server_net:
        ipv4_address: 192.168.200.2

  client:
    build:
      context: ./client
    dns:
      - 172.17.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: client
    networks:
      server_net:
        ipv4_address: 192.168.200.3

networks:
  server_net:
    driver: bridge
    name: my-domain
    ipam:
     config:
       - subnet: 192.168.200.0/24
         gateway: 192.168.200.1