version: '3.5'

services:
  service:
    network_mode: "host"
    build:
      context: ./service
    ports:
      - "3000:3000"

  client:
    network_mode: "host"
    build:
      context: ./client
